### ISSUE TITLE
Segmentation DeepLab V3 architecture.

### ISSUE THREAD

**Issue by Heonjin** [zhanghang1989/ResNeSt#104]
In your paper, you used "DeepLabV3" not "DeepLabV3+". And in the paper of "DeepLabV3", there is a Multi-Grid method. Did you use this method? I want to know How many blocks you used for the DeepLabV3 with ResNeSt.
![image](https://user-images.githubusercontent.com/50353282/89105927-5ec2e000-d460-11ea-8b41-af8e32a3ce82.png)

**Comment by zhanghang1989** [comment]
Models are open sourced at https://hangzhang.org/PyTorch-Encoding/model_zoo/segmentation.html#ade20k-dataset

We only DeepLabV3 head. The mutli-grid is not used.
