### ISSUE TITLE
Can you share the cascade rcnn resnest code?

### ISSUE THREAD

**Issue by cpboost** [zhanghang1989/ResNeSt#106]
I am able to modify the resnest backbone network in mmdet 1.x version,  But the effect is not very good

**Comment by zhanghang1989** [comment]
Please checkout our `pretrained model`, `config`, and `training log` using detectron2 

https://github.com/zhanghang1989/detectron2-ResNeSt

**Comment by zhanghang1989** [comment]
This issue should be resolved.
