### ISSUE TITLE
Could you provide your average latency data?

### ISSUE THREAD

**Issue by cmsflash** [zhanghang1989/ResNeSt#112]
Hi authors, I read your paper. It's an impressive work. It seems that your paper only reported latency in a figure, which does not give accurate data. Could you provide them in a table so that we can get accurate data?

**Comment by zhanghang1989** [comment]
Hi, we have the `frame per sec` reported in Table 4.

**Comment by cmsflash** [comment]
Hi Hang, thank you for responding so timely! There is `img/sec` reported in Table 4 for ResNeSt-101 to 269. In comparison, the figure to the left additionally has `avg latency` for ResNeSt-50. Could you also provide that number? In addition, it would be great if you also have the numbers for corresponding ResNets under the same settings.

**Comment by zhanghang1989** [comment]
%%%%%%%%%%ResNet%%%%%%%%%%%%%
% resnet50b@224: 725.45
% resnet101b@224: 475.28
% resnet152b@224: 348.17
%%%%%%%%%%ResNeXt%%%%%%%%%%%%%
% resnext50_32x4d@224: 560.70
% resnext101_32x4d@224: 345.62
% resnext101_64x4d@224: 210.02
%%%%%%%%%%ResNeSt%%%%%%%%%%%%%
% resnest50@224: 488.17
% resnest50@256: 404.84
% resnest50@320: 273.74
% resnest101@224: 313.29
% resnest101@256: 265.30
% resnest101@320: 176.11
% resnest152@224: xxx.x
% resnest152@256: 199.74
% resnest152@320: 132.77
% resnest200@320: 102.93
% resnest269@400: 54.62
%%%%%%%%%%EfficientNet%%%%%%%%%%%%%
% efficientnet-b0@224: 806.45
% efficientnet-b1@240: 588.24
% efficientnet-b2@260: 458.71
% efficientnet-b3@300: 337.84
% efficientnet-b4@380: 149.25
% efficientnet-b5@456: 84.32
% efficientnet-b6@528: 53.93
% efficientnet-b7@600: 34.92
%%%%%%%%%%SENet%%%%%%%%%%%%%
% SENet-154@224: 133.80
% SENet-154@320: 133.80

**Comment by cmsflash** [comment]
Thank you so much!
