### ISSUE TITLE
can we convert network to libtorch  by torch script and libcaffe (for object detection and segmentation)

### ISSUE THREAD

**Issue by jackft2** [zhanghang1989/ResNeSt#113]
above all

**Comment by zhanghang1989** [comment]
You may give a try. 
link to object detection & instance segmentation https://github.com/zhanghang1989/detectron2-ResNeSt
link to semantic segmentation https://hangzhang.org/PyTorch-Encoding/model_zoo/segmentation.html

**Comment by zhanghang1989** [comment]
ResNeSt is also adopted by MMDetection https://github.com/open-mmlab/mmdetection/tree/master/configs/resnest.
