### ISSUE TITLE
batchsize设置

### ISSUE THREAD

**Issue by riciche** [zhanghang1989/ResNeSt#116]
您好，我想在自己的数据集上跑下resnest269，显卡是1080Ti, batch设2时显存不够，设1时会报错，请问该修改那些部分，谢谢您

**Comment by zhanghang1989** [comment]
这是什么应用？输入尺寸是多少？
可以考虑使用 PyTorch 的 checkpoint 来节省内存训练 https://pytorch.org/docs/master/checkpoint.html?highlight=checkpoint#torch.utils.checkpoint.checkpoint

**Comment by riciche** [comment]
好，谢谢您，可能我没有表达明白，想尝试在batch为1时跑下nest269

**Comment by zhanghang1989** [comment]
如果一定要在 batch size 为1的情况下跑 resnest，只能使用eval mode：
```
mode.eval()
```
因为这个模型里面有spatial 为1的batch norm layer，这个layer算batchnorm statistics是没有意义的。

**Comment by riciche** [comment]
好的谢谢您
