### ISSUE TITLE
how can i get the code to train the model with my own dataset?

### ISSUE THREAD

**Issue by MrCrazyCrab** [zhanghang1989/ResNeSt#117]
i'm a little confused about the readme, i want to train my own dataset, by i cant found the pytorch code of ResNeSt, is the ResNeSt/scripts/torch/ verify.py just for inference? where is the training code?

**Comment by zhanghang1989** [comment]
Please see the link to the training code:
https://github.com/zhanghang1989/ResNeSt#how-to-train

**Comment by ybxbupt** [comment]
you said: "The training script is in the experiments/segmentation/ folder"
but no "experiments/segmentation/ folder" could be found

**Comment by zhanghang1989** [comment]
https://github.com/zhanghang1989/PyTorch-Encoding/tree/master/experiments/segmentation

**Comment by ybxbupt** [comment]
thank you for your reply
