### ISSUE TITLE
rectified conv not included?

### ISSUE THREAD

**Issue by power0341** [zhanghang1989/ResNeSt#12]
It seems the default setting doesn't utilize the rfconv module, however, for curiosity's sake, where may I find a reference of it?

**Comment by zhanghang1989** [comment]
Thanks for your interest. I will give you an update later.

**Comment by ipScore** [comment]
Hi, @zhanghang1989 
Does `rfconv` link to this wheel? `https://pypi.org/project/rfconv/#files`

**Comment by swang-sjtu** [comment]
> Thanks for your interest. I will give you an update later.

The same question, I didn't find any reference to this RFConv2d and deep_stem, could you please provide any reference? Thanks a lot!

**Comment by snowzjy** [comment]
> Thanks for your interest. I will give you an update later.

Very  appreciat

**Comment by zhanghang1989** [comment]
> https://github.com/zhanghang1989/PyTorch-Encoding/blob/b872eb8cc01f6e0dde3d9acfb5846abe5c3a450a/encoding/nn/rectify.py

I will share an arXiv report later. Please kindly do not distribute it for now.

If using it in your research, please cite it as:

```
@article{zhang2020rectified,
title={Rectified Convolution},
author={Zhang, Hang},
journal={arXiv preprint},
year={2020}
}
```

**Comment by zhanghang1989** [comment]
Open sourced at https://github.com/zhanghang1989/RFConv
