### ISSUE TITLE
train ResNeSt in mmdetection

### ISSUE THREAD

**Issue by zoujinger** [zhanghang1989/ResNeSt#120]
hello, I am wondering how to use ResNeSt in mmdetection?
I found mmdetection-ResNeSt in you GitHub, but it has no guidance about how to use.
Thanks and looking forward to your reply.

**Comment by zhanghang1989** [comment]
Looks like the mmdetection team will support ResNeSt officially https://github.com/open-mmlab/mmdetection/pull/2959

**Comment by zhanghang1989** [comment]
This can be closed. ResNeSt has been adopted by MMDetection https://github.com/open-mmlab/mmdetection/tree/master/configs/resnest
