### ISSUE TITLE
different reults on resnest50 with your provided pretrained model

### ISSUE THREAD

**Issue by kickingass** [zhanghang1989/ResNeSt#121]
top1 top5 80.958 95.382 tested on imgnet, but your result is 81.03 for top1.

**Comment by zhanghang1989** [comment]
Can you check whether your val set is complete?

**Comment by zhanghang1989** [comment]
FYI, this score is generate automatically https://cv.gluon.ai/model_zoo/classification.html

**Comment by kickingass** [comment]
5W images for validation total, and the validation code is from https://github.com/bearpaw/pytorch-classification

**Comment by kickingass** [comment]
I use 8 2080tis, maybe that may influence the results?

**Comment by zhanghang1989** [comment]
Please use our evaluation code https://github.com/zhanghang1989/ResNeSt#torch-model
The difference may be because of different data augmentation.
