### ISSUE TITLE
How to use resnest replacement resnet ?

### ISSUE THREAD

**Issue by limoran233** [zhanghang1989/ResNeSt#123]
hello, I want to use your model to replacement resnet in my own vodeo object segmentation network , how can I get your pretrained model resnest101 (pytorch, on ImageNet)?   How to use it ? Should I directly train and evaluate my own network using the pretrained model? Waiting for your reply ,thanks.

**Comment by zhanghang1989** [comment]
Please refer to the README to use the pretrained models https://github.com/zhanghang1989/ResNeSt#pytorch-models
