### ISSUE TITLE
Extra Bias term in SplAtConv2d

### ISSUE THREAD

**Issue by n2cholas** [zhanghang1989/ResNeSt#125]
Thanks so much for providing an implementation and checkpoints for your paper!! Quick question about `SplAtConv2d`:

[Lines 39-41](https://github.com/zhanghang1989/ResNeSt/blob/73b43ba63d1034dbf3e96b3010a8f2eb4cc3854f/resnest/torch/splat.py#L39-L41) has the following:
```python
        self.fc1 = Conv2d(channels, inter_channels, 1, groups=self.cardinality)
        if self.use_bn:
            self.bn1 = norm_layer(inter_channels)
```
But shouldn't the bias in `self.fc1` be disabled when `self.use_bn == True`, like what is done on [lines 33-34](https://github.com/zhanghang1989/ResNeSt/blob/73b43ba63d1034dbf3e96b3010a8f2eb4cc3854f/resnest/torch/splat.py#L33-L34)?  I think it should be:
```python
        self.fc1 = Conv2d(channels, inter_channels, 1, groups=self.cardinality, bias=bias)
        if self.use_bn:
            self.bn1 = norm_layer(inter_channels)
```
Thanks!

**Comment by zhanghang1989** [comment]
Agree. The bias in `fc1` can be disabled.

**Comment by n2cholas** [comment]
Thanks @zhanghang1989!! I'm working on a re-implementation of this model in JAX [here](https://github.com/n2cholas/jax-resnet), and found this when ensuring the parameter counts matched.
