### ISSUE TITLE
DropBlock not implemented

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [zhanghang1989/ResNeSt#129]
Dear all,

The paper says dropblock was, used, but It is not implemented (https://github.com/zhanghang1989/ResNeSt/blob/73b43ba63d1034dbf3e96b3010a8f2eb4cc3854f/resnest/torch/resnet.py#L17)

I am reimplementing this architecture in a more human readable way and I was wondering why the paper says one thing and the code another, probably I am missing something. Thank a lot in advance.

Take care and cheers,

Francesco

**Comment by zhanghang1989** [comment]
Thanks for interest in this work.

The `DropBlock` is only used during the training. All models were trained using MXNet implementation. The DropBlock is used here https://github.com/zhanghang1989/ResNeSt/blob/master/resnest/gluon/resnet.py#L50 . 

The pytorch implementation is converted from MXNet one.

**Comment by FrancescoSaverioZuppichini** [comment]
Thank you for the blazing fast reply! super cool implementation :)
