### ISSUE TITLE
Question regarding AutoAug

### ISSUE THREAD

**Issue by LXXXXR** [zhanghang1989/ResNeSt#144]
Hi, 
Thank you for your work.
In the implementation of AutoAug, official implementation of FAA is referred to. 
https://github.com/zhanghang1989/ResNeSt/blob/43c1c4b5c91898c75a50fd70867f32c6cd9aeef5/resnest/torch/transforms/autoaug.py#L9
However, the implementation in this repo varies from that in FAA. The policies searched by FAA is actually not adapted: the probability for each transform to be applied is fixed to 0.5, the magnitude is also fixed for all transforms in `rand_augment_list` and the subpolicies are not specified.
The difference really confuses me. Could you please tell me if there is any specific reasons for the tweak?
Thank you.

**Comment by zhanghang1989** [comment]
For more information about auto aug, fast AA and rand AA, please visit this repo:

https://github.com/zhanghang1989/Fast-AutoAug-Torch

**Comment by LXXXXR** [comment]
Thank you for the kind reply. The link surely clears things up.
