### ISSUE TITLE
Question about lighting

### ISSUE THREAD

**Issue by LXXXXR** [zhanghang1989/ResNeSt#145]
Hi, 
Thank you for your awesome work.
https://github.com/zhanghang1989/ResNeSt/blob/43c1c4b5c91898c75a50fd70867f32c6cd9aeef5/resnest/torch/transforms/transforms.py#L16-L34
Just a tiny question about lighting. It seems to me that the intention of PCA color augmentation is to alter the intensities of the RGB channels using principal component. However, if we add `rgb` to `img` without changing its dtype, `img` may easily suffer from overflow therefore might not give the correct augmented img we desire. Why isn't that a concern?

**Comment by zhanghang1989** [comment]
Hi, The lighting is actually added after toTensor https://github.com/zhanghang1989/ResNeSt/blob/43c1c4b5c91898c75a50fd70867f32c6cd9aeef5/resnest/torch/transforms/build.py#L34

So the image is already in float type.

**Comment by LXXXXR** [comment]
Got it. So we should not concern too much whether the value of RGB pixel actually exceed the correct range of RGB value, right? Thank you very much.
