### ISSUE TITLE
Module code

### ISSUE THREAD

**Issue by David-19940718** [zhanghang1989/ResNeSt#15]
Hello, can you give a separate module code for the ResNeSt (pytorch version)? 
For example, like Res-block in ResNet, I want to embed it in my network to try the effect.

**Comment by zhanghang1989** [comment]
Hi, the ResNeSt-bottleneck block is defined at https://github.com/zhanghang1989/ResNeSt/blob/master/resnest/torch/resnet.py#L29

You may standard bottleneck block with this one and set `radix=2` or `radix=4`

**Comment by zhanghang1989** [comment]
The module is provided at https://github.com/zhanghang1989/ResNeSt/issues/66
