### ISSUE TITLE
TypeError: load_state_dict_from_url() got an unexpected keyword argument 'check_hash'

### ISSUE THREAD

**Issue by cendelian** [zhanghang1989/ResNeSt#16]
hi when I run command:
```
import torch
# get list of models
torch.hub.list('zhanghang1989/ResNeSt', force_reload=True)

# load pretrained models, using ResNeSt-50 as an example
net = torch.hub.load('zhanghang1989/ResNeSt', 'resnest50', pretrained=True)
```

or
```
from ResNeSt.resnest.torch.resnest import resnest50
model = resnest50(pretrained=True)
```

there is a error:
**TypeError: load_state_dict_from_url() got an unexpected keyword argument 'check_hash'**

what is it?
could you help me

**Comment by cendelian** [comment]
I remove the check_hash=Ture
and no problem

thanks

**Comment by clw5180** [comment]
> I remove the check_hash=Ture
> and no problem
> 
> thanks

Thanks !

**Comment by Lin-plax** [comment]
Can you tall me how to remove it? Delete it from source code? Thanks

**Comment by Lin-plax** [comment]
I have run the ResNeSt in fastai,
learn = fastai.vision.cnn_learner(data, resnest50(pretrained=True), metrics=[accuracy])
and the error is 
load_state_dict_from_url() got an unexpected keyword argument 'check_hash'
Thanks!

**Comment by zhanghang1989** [comment]
That's mainly because the PyTorch version, please use `torch>=1.4.0`
