### ISSUE TITLE
1x1convolution 

### ISSUE THREAD

**Issue by Vegetabhl** [zhanghang1989/ResNeSt#163]
This line of code in splatconv2d
self.conv = Conv2d(in_channels, channels * radix, kernel_size, stride, padding, dilation,
                         groups=group * radix, bias=bias, **kwargs) 

My understanding is that the input feature map is divided into {group * radius}，Each {radix} is a group，According to the principle of equivalence, there will be 3x3 convolution in each group(kernel_size=3)，But I can't find the 1x1 convolution in the group on the graph in the paper? I don't seem to find it in the code?

**Comment by zhanghang1989** [comment]
There is a conv 1x1 after concatenation:

![image](https://user-images.githubusercontent.com/8041160/130655226-cb46d3d1-2205-414e-a714-f9f80dbb0592.png)

**Comment by Vegetabhl** [comment]
![1](https://user-images.githubusercontent.com/59409902/130727832-693ae2bd-ade4-4f2a-89bd-a561e6cd04a9.png)

First of all, thank you for your reply。In splatconv2d，I looked at the code, which seems to correspond to this figure。But I didn't find the 1 * 1 convolution marked on the figure in the code。

**Comment by zhanghang1989** [comment]
That figure shows the entire bottleneck block:
https://github.com/zhanghang1989/ResNeSt/blob/master/resnest/torch/models/resnet.py#L41
