### ISSUE TITLE
How about ResNeSt-18/34 which using BasicBlock with Split-Attention unit?

### ISSUE THREAD

**Issue by lynlynlyn96** [zhanghang1989/ResNeSt#21]
Hi Have you ever tried to use BasicBlock with split-attention unit for the ResNeSt-18 or ResNeSt-34?
Do you think resnest10 is OK?

**Comment by ruiming46zrm** [comment]
same questioin

**Comment by ruiming46zrm** [comment]
resne**s**t50 performs the same accuracy on my face quality classification as my basic res18 network~~
maybe the network too large and 2048 is not well adaptive for 112*112 face img

**Comment by zhanghang1989** [comment]
Despite that doesn't align with our original motivation of designing it, I would expect it work as well. 

It may be worth a try.

**Comment by zhanghang1989** [comment]
> resne**s**t50 performs the same accuracy on my face quality classification as my basic res18 network~~
> maybe the network too large and 2048 is not well adaptive for 112*112 face img

The transfer learning performance depends on many factors, such as dataset scale, domain difference and network capacity. We don't expect the ResNeSt performs well on all tasks :)

**Comment by zhanghang1989** [comment]
FYI, GluonCV just added `ResNeSt-26` with a top-1 accuracy of 78.69 https://github.com/dmlc/gluon-cv/pull/1263

**Comment by SohamTamba** [comment]
They use BottleNeck instead of BasicBlock.
I wonder if that'll be a problem.

**Comment by zhanghang1989** [comment]
The reason of using Bottleneck block is because it better fits the paper's story, but I think the Basic block should also work.

**Comment by yemenr** [comment]
@zhanghang1989 @SohamTamba  I have tried a resnet50 with basicblock. But in this case, the splat is not as good as I expect. Can someone also try basicblock instead of bottleneck?
