### ISSUE TITLE
Confusing Part in the Code

### ISSUE THREAD

**Issue by EternalConfession** [zhanghang1989/ResNeSt#23]
You defiend the number of output channel as
https://github.com/zhanghang1989/ResNeSt/blob/a1f20b89b7e2ca7da628c646be174807076b1991/resnest/torch/splat.py#L52

and split size as
```python
channel // self.radix
```

But it is equal to something that is already defined as:
https://github.com/zhanghang1989/ResNeSt/blob/a1f20b89b7e2ca7da628c646be174807076b1991/resnest/torch/splat.py#L26

The name and usage of these variables are a little bit confusing. Maybe you could change the name a little bit.

**Comment by zhanghang1989** [comment]
Thanks for pointing out. Will rename the variable to avoid confusion.
