### ISSUE TITLE
PyTorch version

### ISSUE THREAD

**Issue by qubvel** [zhanghang1989/ResNeSt#24]
Hi @zhanghang1989 
Thanks for your work, could you please clarify why PyTorch should be later than 1.4 version?

**Comment by zhanghang1989** [comment]
It's a pure python package. It should be compatible with earlier version as well.

**Comment by qubvel** [comment]
Could you please make torch>=1.0 requirement? I would like to add you network to my package https://github.com/qubvel/segmentation_models.pytorch

**Comment by zhanghang1989** [comment]
Sure. Will do it in next version. Thanks!

**Comment by zhanghang1989** [comment]
This issue has been resolved, see https://github.com/zhanghang1989/ResNeSt/blob/master/setup.py#L39

**Comment by qubvel** [comment]
Thanks, waiting for new PyPI release to merge)

**Comment by zhanghang1989** [comment]
Thanks. We will tag 0.0.3 around this weekend.
