### ISSUE TITLE
How to train resnest backbone with DCN v2?

### ISSUE THREAD

**Issue by hanjianhua44** [zhanghang1989/ResNeSt#39]
Code lab is based on mmdetection, which already has the deformconvpack

**Comment by chongruo** [comment]
Thanks for your interests. We have tried to incorporate the deformable conv into ResNeSt-detectron2. Here is the [draft version](https://github.com/zhanghang1989/detectron2-ResNeSt/tree/dcn). Basically, we replace the standard conv with deformable conv in specified bottlenecks. The modification would be similar in mmdetection.

Currently, we do not have the implementation of ResNeSt in mmdetection, but definitely it is on our plan. Stay tuned.

**Comment by hanjianhua44** [comment]
@chongruo  @zhanghang1989 Thanks for your answers. After changing the number of deform_num_groups to 2 and fix some bugs, things still happens that the loss is much bigger than the one without DCN, thus the mAP is much lower, even with the resnest50. Have you faced the same proplems?

**Comment by chongruo** [comment]
> @chongruo @zhanghang1989 Thanks for your answers. After changing the number of deform_num_groups to 2 and fix some bugs, things still happens that the loss is much bigger than the one without DCN, thus the mAP is much lower, even with the resnest50. Have you faced the same proplems?

We are running experiments with dcn. Will share the model/log later. Thanks

**Comment by chongruo** [comment]
We have released the model/log of Faster-rcnn-ResNeSt50-DCNv2 https://github.com/zhanghang1989/detectron2-ResNeSt
