### ISSUE TITLE
Why permuting the dimension in rSoftMax?

### ISSUE THREAD

**Issue by Andy1621** [zhanghang1989/ResNeSt#41]
Hello! Thanks for your great job!!!
I have read your codes about split attention and I found a problem as follows, 
https://github.com/zhanghang1989/ResNeSt/blob/0417a092a1dc27d6372f390e0b18cb91da9106b5/resnest/torch/splat.py#L87

Why permuting the dimension in rSoftMax? Why not
```python3
x = x.view(batch, self.cardinality, self.radix, -1)
x = F.softmax(x, dim=2)
x = x.reshape(batch, -1)
```
I think it's the right way to map the attention. Do I make a mistake? Is there anything I have ignored?

**Comment by zhanghang1989** [comment]
Good question.

This is radix-major implementation. After sum across different splits, the representation of the attention factor becomes cardinality-major, so we need to swap the order of cardinality and radix to align with the radix-major feature-map before channel-wise attention. 

You may take a look at the unit test for equivalent implementation:

https://github.com/zhanghang1989/ResNeSt/blob/master/tests/test_radix_major.py

**Comment by zhanghang1989** [comment]
The figure in https://github.com/zhanghang1989/ResNeSt/issues/4#issuecomment-616144407 would also help.

**Comment by zhanghang1989** [comment]
Since you have figured that out, this issue can be closed.
