### ISSUE TITLE
About AvgPool2d order in Bottleneck may not as designed?

### ISSUE THREAD

**Issue by QiaoranC** [zhanghang1989/ResNeSt#43]
Hi:
   I am trying to rewrite it in TF, and so far there is one thing i get confused.
   I noticed in the bottleneck, the `avd_layer` can be before or after the `conv2` based on `self.avd` and `self.avd_first.`
  In resnest50, the `avd_layer` should following the `conv2`,(i print it to check).

```
        if self.avd and self.avd_first:
            out = self.avd_layer(out)
            # print('cannt')
        out = self.conv2(out)
        if self.radix == 0:
            out = self.bn2(out)
            if self.dropblock_prob > 0.0:
                out = self.dropblock2(out)
            out = self.relu(out)

        if self.avd and not self.avd_first:
            # print('can')
            out = self.avd_layer(out)
```

However, when i print the model, it seems `avd_layer` is before the `Conv2d`, which is confusing. 

```
  (layer2): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (avd_layer): AvgPool2d(kernel_size=3, stride=2, padding=1)
      (conv2): SplAtConv2d(
        (conv): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=2, bias=False)
        (bn0): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (fc1): Conv2d(128, 64, kernel_size=(1, 1), stride=(1, 1))
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (fc2): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1))
        (rsoftmax): rSoftMax()
      )
      (conv3): Conv2d(128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): AvgPool2d(kernel_size=2, stride=2, padding=0)
        (1): Conv2d(256, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
```

Is there something i miss? Thanks

**Comment by zhanghang1989** [comment]
Hi, thanks for the effort for converting the model into TF. Let me know if you are done, I will add a link to your github repo.

`avd_first` means putting average pooling layer before convolution. This is used in models with fast setting:
- see results in https://github.com/zhanghang1989/ResNeSt/blob/master/ablation.md 
- model defination at https://github.com/zhanghang1989/ResNeSt/blob/master/resnest/torch/ablation.py#L42)

**Comment by zhanghang1989** [comment]
Just to make it clear, the average pooling is after the convolution in standard setting of `ResNeSt-{50, 101, 200, 269}`

**Comment by QiaoranC** [comment]
@zhanghang1989 Thanks for you explain, and sorry for the delay. I finished it a while ago, but just publish it. here is the address, model only https://github.com/QiaoranC/tf_ResNeSt_RegNet_model .
i also add RegNet, interestingly, RegNet was my first choice to reproduce, but it didnot perform well in my project, so then i chose ResNest, it did good, and also quite complicated, anyway, thanks for you sharing.

**Comment by zhanghang1989** [comment]
Thanks @QiaoranC ! Great job. I will add a link to your repo.

**Comment by zhanghang1989** [comment]
Link added in this PR https://github.com/zhanghang1989/ResNeSt/pull/54
