### ISSUE TITLE
Error with BatchNorm2d in 'SplAtConv2d' when training

### ISSUE THREAD

**Issue by chrisway613** [zhanghang1989/ResNeSt#46]
https://github.com/zhanghang1989/ResNeSt/blob/fd76fabe82691f3b8f391e67b16d734404dff8cd/resnest/torch/splat.py#L65

After global average pooling, the feature size becomes 1x1 per channel, if use BN here when training, it will report the error as below:
  ValueError: Expected more than 1 value per channel when training
Since BN is a kind of channel-wise normalization.

**Comment by zhanghang1989** [comment]
For training, the batch-size has to be greater than 1, and ideally should be greater than 16. 
It is okay for evaluation model for a single sample.

**Comment by chrisway613** [comment]
Oh, I set the batch-size to 1 by careless when testing this module, sorry...

**Comment by zhanghang1989** [comment]
No worries. `model.eval()` should work.
Mark this as resolved.
