### ISSUE TITLE
Program Stucks when using naivesyncBN of detectron2

### ISSUE THREAD

**Issue by hanjianhua44** [zhanghang1989/ResNeSt#47]
torch.syncBN has known issues, so I transfer naivesyncBN of detectron2 to mmdetection.

But after I use naivesyncBN with resnest, the program always stucked after some iterations, so I need to resume from such checkpoint.

I have seen you answered some question like syncBN may get your program stucked after some iterations. So I wonder if I can get some advices from you.

Basic settings:
mmdetion 1.0.0
naivesyncBN from detectron2 v0.1
pytorch 1.1.0
cuda 9
cudnn7.0
use 6 nodes, 8 GPU each node

**Comment by chongruo** [comment]
For training models in detectron2, we never observe any issues with SyncBN.

**Comment by hanjianhua44** [comment]
Thanks for the reply, maybe there is some problem with my enviorment.
