### ISSUE TITLE
NaN loss occurs

### ISSUE THREAD

**Issue by msha096** [zhanghang1989/ResNeSt#51]
Thanks for your great work! I am using ResNest as the backbone of my detector, but the loss values turns out to be nan. Previously I was using ResNet as the backbone and the losses are normal. 

I use the focal loss function in the classification branch, and the loss value of this branch is a fixed value at every iteration and epoch. As for the regression branch, where I use the Smooth L1 loss function, the loss value turns out to be nan.

Could you please help me out? Thanks!

**Comment by chongruo** [comment]
Could you provide more details? Which framework are you using? what is config.yaml?

**Comment by msha096** [comment]
> Could you provide more details? Which framework are you using? what is config.yaml?

Hi, I am using a one-stage detector, and I am using ResNest in the feature extraction phase. The detection head is pretty simple like using some parallel 1x1 Conv layers to classify and regress. I was using ResNet and the results are good.  I am confused about why the loss values are nan when I apply ResNest in the backbone....

**Comment by msha096** [comment]
> Could you provide more details? Which framework are you using? what is config.yaml?

I used Adam with lr 5e-5, which I think is small enough. I use the same dataset and the same data augment/pre-process. Is there anything else you need to know?

**Comment by chongruo** [comment]
Are you using detectron2? or other framework (mmdetection, maskrcnn-benchmark)?

One possible reason is that the input mean and std are not set correctly. In some frameworks, std is [1,1,1] by default. Please also change the input order to 'RGB'.
