### ISSUE TITLE
Small performance improvement in attention module

### ISSUE THREAD

**Issue by rwightman** [zhanghang1989/ResNeSt#59]
Hi @zhanghang1989, thanks for the great models.

I recently added your ResNeST models to my collection. I made a small tweak to the the attention module that improved forward throughput by approx 10%, did not check backward. Basically I changed the split/python sum to reshape + torch sum. I actually started making the change to allow torchscript compatibility of your model and noticed it had a positive impact on img/s. 

https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/layers/split_attn.py

**Comment by zhanghang1989** [comment]
Awesome. Thank you very much for pointing out the implementation! 
We will test the training time and get back to you.
