### ISSUE TITLE
[Question] mxnet resnest, after using  tvm  is too slow

### ISSUE THREAD

**Issue by lichun-wang** [zhanghang1989/ResNeSt#60]
Hi,
I downloaded resnest from gluon and converted it to mxnet model(json + params). Then I used tvm auto tune to make the model  faster on 1080ti.  But after tuning , the model became too slow .  mxnet model take 15ms to process a image, but after tuning, it will take 380ms, I don't find the reason.

**Comment by zhanghang1989** [comment]
Thanks for reporting the issue! 
Looks like a TVM issue, please consider reporting it to TVM.
