### ISSUE TITLE
Equation (3) in the paper

### ISSUE THREAD

**Issue by Jimenius** [zhanghang1989/ResNeSt#62]
I think there's a minor error in the equation (3) of the paper. Should the summation in softmax be from 1 to R?

**Comment by zhanghang1989** [comment]
> I think there's a minor error in the equation (3) of the paper. Should the summation in softmax be from 1 to R?

Thanks for the feedback! 
Agree. It should be *1* to *R* instead of *0* to *R*. A programer's habit.
