### ISSUE TITLE
 ResNest Caffe format ?

### ISSUE THREAD

**Issue by china56321** [zhanghang1989/ResNeSt#68]
Could you provide  ResNest Caffe format   ?

**Comment by zhanghang1989** [comment]
Sorry that I don't use Caffe. Let's wait for the community contribution.

**Comment by zhifanlight** [comment]
@china56321 @zhanghang1989 
Hi, we just convert ResNeSt models by pytorch-onnx-caffe. See https://github.com/NetEase-GameAI/ResNeSt-caffe

**Comment by zhanghang1989** [comment]
> @china56321 @zhanghang1989
> Hi, we just convert ResNeSt models by pytorch-onnx-caffe. See https://github.com/NetEase-GameAI/ResNeSt-caffe

Thank you very much for the contribution! I will add a link to your repo.
