### ISSUE TITLE
Gluon and Torch use different optimizers

### ISSUE THREAD

**Issue by vchiley** [zhanghang1989/ResNeSt#69]
The [gluon training script](https://github.com/zhanghang1989/ResNeSt/blob/master/scripts/gluon/train.py) [uses](https://github.com/zhanghang1989/ResNeSt/blob/master/scripts/gluon/train.py#L355) the [mxnet nag optmizer](https://beta.mxnet.io/api/gluon-related/_autogen/mxnet.optimizer.NAG.html).
[PyTorch training](https://github.com/zhanghang1989/ResNeSt#imagenet-models) is accessed through the [PyTorch Encoding Toolkit](https://hangzhang.org/PyTorch-Encoding/model_zoo/imagenet.html). If you track down the code you see that the [pytorch code uses SGDM](https://github.com/zhanghang1989/PyTorch-Encoding/blob/master/experiments/recognition/train_dist.py#L211) instead of NAG.
[Results seem to be unaffected](https://github.com/zhanghang1989/ResNeSt#pretrained-models) but there is a difference.

**Comment by zhanghang1989** [comment]
Thanks for pointing out!
Yeah. Based on our experience, the results are usually close using NAG or SGD.
