### ISSUE TITLE
Is the crop size for ResNeSt fixed to 224?

### ISSUE THREAD

**Issue by KaqiKaqi** [zhanghang1989/ResNeSt#7]
Hello, I'd like to use ResNeSt as backbone in Retinanet to replace ResNet as a feature extractor. Is it possible to use a larger image input size with the given pretrained models? Thanks a lot!

**Comment by zhanghang1989** [comment]
Yes. ResNeSt has the same meta model structure with standard ResNet, so it should be straightforward to be adopted in RetinaNet. 

Based on our experience on Faster R-CNN, ResNeSt usually gives 3% improvement on mAP comparing to standard ResNet.

**Comment by KaqiKaqi** [comment]
Thanks a lot!
