### ISSUE TITLE
ResNest18 and ResNeSt34

### ISSUE THREAD

**Issue by xungeer29** [zhanghang1989/ResNeSt#72]
Will ResNest18 and ResNeSt34 pretrained models be released?

**Comment by zhanghang1989** [comment]
18 and 34 layer ResNet use BasicBlock, which is incompatible with the  original motivation of designing Split-attention block in the paper (due to the story).

Some mentioned that the results are not very good https://github.com/zhanghang1989/ResNeSt/issues/21
