### ISSUE TITLE
Different from SKNet

### ISSUE THREAD

**Issue by Xujianzhong** [zhanghang1989/ResNeSt#74]
@zhanghang1989 Thank you for your work.
I have some questions. When Cardinal is 1, what's the difference between ResNeSt and SKNet?

**Comment by zhanghang1989** [comment]
The slight difference is that the input channels are split in ResNeSt.

**Comment by Jimenius** [comment]
I have similar questions.  In the Bottleneck module, conv1 is outside the split attention module. I think this implementation is different from Fig 1. in the paper and also different from  in Radix-major figure in #4.

In my understanding, when radix=2 and cardinality=1, the difference between ResNeSt and SKnet is ResNeSt uses 3x3 conv only, which can be optimized by group convolution. Is that right?

**Comment by Jimenius** [comment]
I have similar questions. In the Bottleneck module, conv1 is outside the split attention module. I think this implementation is different from Fig 1. in the paper and also different from in Radix-major figure in #4.

In my understanding, when radix=2 and cardinality=1, the difference between ResNeSt and SKnet is ResNeSt uses 3x3 conv only, so it can actually implemented in a single conv layer as in conv2.conv. Is that right?

**Comment by zhanghang1989** [comment]
Hi, thanks for the question. Please refer to the Appendix of the paper for Radix-major implementation: https://arxiv.org/pdf/2004.08955.pdf

and the 知乎 link https://zhuanlan.zhihu.com/p/135220104

**Comment by Xujianzhong** [comment]
@zhanghang1989 Thanks !

**Comment by ignitemylife** [comment]
> @zhanghang1989 Thank you for your work.
> I have some questions. When Cardinal is 1, what's the difference between ResNeSt and SKNet?
其实我细看文章的时候，也有相同的疑问： 当2s1x64D配置的时候，究竟和SKNet区别有多大？ 
仔细想了一下： ResNeSt是每个Cardinality中split后（c/k/r）再各自3x3卷积得到c/k维度的特征，然后再split-attention得到attention, 而SKNet是对同一个feats, 不同的kernel, 相同之处在于两者的split-attention是一模一样
