### ISSUE TITLE
No bias convLayer?

### ISSUE THREAD

**Issue by TanFluent** [zhanghang1989/ResNeSt#76]
hi, 
   i notice that, when init a conv layer, some with a "bias" term, but some are not. Can you exprand why using a "no bias conv"?. Are there any principle when init a conv-layer?

[no-bias]
https://github.com/zhanghang1989/ResNeSt/blob/31444ed2ff446aa218c6b29f00a433bd5d4ae7cd/resnest/torch/resnet.py#L41

[with-bias]
https://github.com/zhanghang1989/ResNeSt/blob/31444ed2ff446aa218c6b29f00a433bd5d4ae7cd/resnest/torch/splat.py#L42

**Comment by zhanghang1989** [comment]
Thanks! `self.fc1` and `self.fc2` are actually using convolutional layer to implement FC layer. 
We explains the radix implementation in the paper appendix.
