### ISSUE TITLE
why the groups always 1?

### ISSUE THREAD

**Issue by XianYuZhiWang** [zhanghang1989/ResNeSt#77]
when build resnest molel in ResNeSt/resnest/torch/resnest.py, why the parameter: groups always 1？groups means the number cardinalities, if it should be 2 at least?

**Comment by ACbccc** [comment]
您好，请问您现在知道原因了吗？我刚看代码，也有同样的疑惑

**Comment by zhanghang1989** [comment]
More models are available at https://github.com/zhanghang1989/ResNeSt/blob/master/ablation.md
