### ISSUE TITLE
weight

### ISSUE THREAD

**Issue by lijain** [zhanghang1989/ResNeSt#80]
Thank you for sharing this project. I would like to ask you where is the weight of this pre training download?
I found the address below:
https://hangzh.s3-us-west-1.amazonaws.com/encoding/models/resnest101_detectron-486f69a8.pth
Can be applied to non detectors projects? If not, please send a pre training weight address that can be used

**Comment by zhanghang1989** [comment]
You can easily load the pretrained models using the command here https://github.com/zhanghang1989/ResNeSt#pytorch-models

Then you may use ``net.state_dict()`` to get the weight.
