### ISSUE TITLE
batchsize

### ISSUE THREAD

**Issue by lijain** [zhanghang1989/ResNeSt#81]
你好，我想问下我总数据集是44884一块gpu训练，batchsize=2时还是报ValueError：Expected more than 1 value per channel when training，got input size torch.Size([1,32,1,1])。难道是因为我的gpu是1的原因？？

**Comment by zhanghang1989** [comment]
这个情况是batchsize=1的时候引起的，有可能是最后一个batch引起的，你可以再检查一下看看

**Comment by lijain** [comment]
好的，谢谢了！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Hang Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月15日(星期一) 上午10:49
收件人:&nbsp;"zhanghang1989/ResNeSt"<ResNeSt@noreply.github.com&gt;;
抄送:&nbsp;"利剑"<1632401541@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhanghang1989/ResNeSt] batchsize (#81)





 
这个情况是batchsize=1的时候引起的，有可能是最后一个batch引起的，你可以再检查一下看看
