### ISSUE TITLE
Unfair comparison between SKNet and ResNeSt?

### ISSUE THREAD

**Issue by khy0809** [zhanghang1989/ResNeSt#82]
Thank you for this great work and code. I have a question.
In the paper, the imagenet classification performances are reported as: 
- SKNet-50 (79.21%)
- ResNeSt-50-fast (80.64%)
The paper says that ResNeSt-50 is trained with additional data augmentation techniques such as AutoAug and Mixup. I also found those two techniques are used in training ResNeSt model from your code (https://hangzhang.org/PyTorch-Encoding/model_zoo/imagenet.html). However, SKNet-50 does not uses those two augmentation techniques. Therefore, maybe your comparison between SKNet-50 and ResNeSt-50-fast is not fair?  

I wonder if you have ever tried training ResNeSt-50 without autoaug and mixup?

**Comment by zhanghang1989** [comment]
That's good question.

In our paper, all the tables are separated using dashed line. Everything above that line is marked as prior work, and everything below that is marked as ours. 

It is good suggestion to compare everything using the same setting, despite we haven't seen other paper does that (such as EfficientNet, SKNet). Actually we did make additional comparisons after the deadline, and would include that in the paper appendix in next version.
