### ISSUE TITLE
Inference time 

### ISSUE THREAD

**Issue by abhigoku10** [zhanghang1989/ResNeSt#83]
@zhanghang1989  thanks for opensourcing your work i have few queries

1. what is fps your getting from the network for the different task like semantic, instance and panpotic segmentation network
2.have you tired on BDD100k dataset or other dataset

**Comment by zhanghang1989** [comment]
You may checkout our detectron fork https://github.com/zhanghang1989/detectron2-ResNeSt
There are training logs available for the train/val throughput

**Comment by abhigoku10** [comment]
@zhanghang1989  thanks for the response
