### ISSUE TITLE
Performance issue about using resnest as backbone network

### ISSUE THREAD

**Issue by ginobilinie** [zhanghang1989/ResNeSt#84]
I have tried to replace resnet50 with resnest50 on a panoptic segmentation network (upsnet), but it turns out the resnest50 gives poorer results. I'm wondering if you have freeze some layers when using resnest as backbone? Have you fix the bn when using it as backbone?

Thanks.

**Comment by zhanghang1989** [comment]
We used SyncBatchNorm for PanopticFCN in detectron. You may see details in https://github.com/zhanghang1989/detectron2-ResNeSt

**Comment by ginobilinie** [comment]
Thanks. 

But I'm not asking which BN you use. I'm asking do you freeze your resnest when you use it as backbone? Since I cannot get better result when using resnest as backbone than resnet.

**Comment by ginobilinie** [comment]
I have followed the details of the setting in your referred link, while it still underperforms the resnet50.

**Comment by zhanghang1989** [comment]
We have provided the `configuration file`, `pretrained model` and `training log` for PanopticFCN https://github.com/zhanghang1989/detectron2-ResNeSt#panoptic-segmentation
