### ISSUE TITLE
Why group is always set to 1? 

### ISSUE THREAD

**Issue by ACbccc** [zhanghang1989/ResNeSt#85]
I used https://github.com/zhanghang1989/ResNeSt/blob/master/resnest/torch/resnest.py to train Resnest-50. When I checked the code I found the hyperparameter of "GROUP" is all set to 1.  I'm confused if group is set to 1 how can cardinality be usiable?

**Comment by zhanghang1989** [comment]
More models are available https://github.com/zhanghang1989/ResNeSt/blob/master/ablation.md

**Comment by clementgr** [comment]
Hi, a part from resnest50_fast_1s1x64d, I can't download the weights of the different models described in https://github.com/zhanghang1989/ResNeSt/blob/master/ablation.md (AccessDenied)

would it be possible to make these weights public too? 
It'd be more convenient for me to download them than using torch.hub.load( )

thank you!

**Comment by zhanghang1989** [comment]
Hi @clementgr , your url format is not correct. Could you try https://s3.us-west-1.wasabisys.com/resnest/torch/resnest50_fast_4s2x40d-41d14ed0.pth

**Comment by zhanghang1989** [comment]
I can add it to torch hub.

**Comment by clementgr** [comment]
damn... sorry for disturbing you, I thought I add tried both combinations...
the url you provided was the right one indeed, thank you very much!

**Comment by zhanghang1989** [comment]
I am working on the torch-hub in https://github.com/zhanghang1989/ResNeSt/pull/93

**Comment by clementgr** [comment]
I'm not sure I got what you meant by "I can add it to torch hub": weren't these weights already available on torch.hub? 
(it's just sheer curiosity as I'm not using torch hub: I'm loading the weights using the .pth files directly).

a quick question related to the topic of this issue: in your paper as well as ResNeXt paper, it's mentioned that increasing cardinality should improve model's performances. for someone not too worried by training time, up to how much do you think one can increase cardinality? (i.e. is there a net difference between groups = 4 and groups = 16)

**Comment by zhanghang1989** [comment]
We tried `2s8x14d`, which gives better results than provided ablation models. 

If you'd like to further increase the number of groups (e.g. mobile setting), we can change the model definition to decouple radix, cardinality and number of groups.

**Comment by zhanghang1989** [comment]
BTW, if you want to load pretrained model, you may simply using the code:
```
from resnest.torch import resnest50_fast_4s2x40d
net = resnest50_fast_4s2x40d(pretrained=True)
```

**Comment by clementgr** [comment]
nice!!
do you have an email I can reach you at? I still have 1-2 unanswered question I'd love to ask you but I don't want to pollute this thread.
thanks

**Comment by zhanghang1989** [comment]
Sure. Feel free to send an email to `hzaws@amazon.com`
