### ISSUE TITLE
Hi! some questions about dropblock.

### ISSUE THREAD

**Issue by wqz960** [zhanghang1989/ResNeSt#88]
Hi! During training for ResNest, the dropblock is used to improve the accuracy, but is dropblock really useful? Have you done comparative experiments and how much drop_prob is in training?
Thank you!!!

**Comment by zhanghang1989** [comment]
Using Dropblock can slightly improve the performance ~0.2% for ResNeSt-50 (sometimes the improvement is not consistent).

**Comment by wqz960** [comment]
Hi！ can you tell me the drop rate for dropblock during training ?
Thank you !

**Comment by zhanghang1989** [comment]
The drop rate is linearly increased from 0 to 0.1.
