### ISSUE TITLE
When will official mmdetection implementation be released?

### ISSUE THREAD

**Issue by kunc01** [zhanghang1989/ResNeSt#89]
Thanks for your great work!
You mentioned in [https://github.com/zhanghang1989/ResNeSt/issues/37#issuecomment-620357337](url) that mmdetection implementation is on your plan, and I'm wondering when will it be released? If it takes too long, I'll try myself:)

**Comment by zhanghang1989** [comment]
The co-authors @chongruo @Jerryzcn and I are quite occupied recently. We are planning to do it sometime in the summer.

**Comment by kunc01** [comment]
Got it. Thanks for your quick reply!
