### ISSUE TITLE
ResNeSt Urls for Detectron Compatible Backbone File

### ISSUE THREAD

**Issue by zhanghang1989** [zhanghang1989/ResNeSt#9]
Use this as a tracker for model urls, will release the Detectron experiments later:

```
https://hangzh.s3.amazonaws.com/encoding/models/resnest50_detectron-b22b3cfa.pth
https://hangzh.s3.amazonaws.com/encoding/models/resnest101_detectron-5667c874.pth
https://hangzh.s3.amazonaws.com/encoding/models/resnest200_detectron-b13b91ae.pth
https://hangzh.s3.amazonaws.com/encoding/models/resnest269_detectron-8e11ab71.pth
```

**Comment by greathope** [comment]
detectron2?  is it possible to train your detection models based on mmdetection?

**Comment by zhanghang1989** [comment]
> detectron2? is it possible to train your detection models based on mmdetection?

@chongruo @Jerryzcn 

It is possible by making some slightly changes to the mmdetection code. We are also planning to send a PR to mmdetection for training with ResNeSt backbone.

**Comment by greathope** [comment]
great, look forward to it

**Comment by chongruo** [comment]
To be compatible with detectron2, the names of pre-trained weights will be changed accordingly.

```
new_name = 'backbone.bottom_up.' + old_name
```

**Comment by zhanghang1989** [comment]
> To be compatible with detectron2, the names of pre-trained weights will be changed accordingly.
> 
> ```
> new_name = 'backbone.bottom_up.' + old_name
> ```

```
https://hangzh.s3-us-west-1.amazonaws.com/encoding/models/resnest50_detectron-255b5649.pth
https://hangzh.s3-us-west-1.amazonaws.com/encoding/models/resnest101_detectron-486f69a8.pth
https://hangzh.s3-us-west-1.amazonaws.com/encoding/models/resnest200_detectron-02644020.pth
https://hangzh.s3-us-west-1.amazonaws.com/encoding/models/resnest269_detectron-69df4066.pth
```

**Comment by 1428679766** [comment]
> tible with detectron2, the names of pre-trained weights will be changed according
Is there a pre-trained model compatible with the maskrcnn-benchmark code base?

**Comment by zhanghang1989** [comment]
> > tible with detectron2, the names of pre-trained weights will be changed according
> > Is there a pre-trained model compatible with the maskrcnn-benchmark code base?

@chongruo is working very hard in cleaning the code. We are planning to release it early next week.

**Comment by zhanghang1989** [comment]
All the detectron models are released.
