### ISSUE TITLE
Cannot Download Models? Please Update the Package

### ISSUE THREAD

**Issue by zhanghang1989** [zhanghang1989/ResNeSt#94]
I have changed the model urls to [Wasabi](https://wasabisys.com/), because it is getting extremely expensive to use S3 (a few hundred dollars per month).

Please **update the package to download the models** from new URLs. Unfortunately, I couldn't provide S3 access any more.

**Comment by rwightman** [comment]
@zhanghang1989 FYI, you can just store them as binaries in a github release

**Comment by zhanghang1989** [comment]
Thanks @rwightman ! Awesome, I didn't know that before. 
The Wasabi option seems cheap enough. I am happy with it for now :)

**Comment by achaiah** [comment]
It seems that the models are still not available in wasabi :(

**Comment by zhanghang1989** [comment]
> It seems that the models are still not available in wasabi :(

Please follow the instruction here to get the model https://github.com/zhanghang1989/ResNeSt#pytorch-models

**Comment by justDoIt1314** [comment]
Who can share this model？Thanks

**Comment by zhanghang1989** [comment]
> Who can share this model？Thanks

The models are available, see instructions https://github.com/zhanghang1989/ResNeSt#pytorch-models

**Comment by justDoIt1314** [comment]
> > Who can share this model？Thanks
> 
> The models are available, see instructions https://github.com/zhanghang1989/ResNeSt#pytorch-models

But I got an error when load this model,
Exception has occurred: TypeError
load_state_dict_from_url() got an unexpected keyword argument 'check_hash'

**Comment by zhanghang1989** [comment]
Which model are you using? 

Could you try again? Sometimes, it may be network issue.

**Comment by justDoIt1314** [comment]
> Which model are you using?
> 
> Could you try again? Sometimes, it may be network issue.

You are right，Thanks！

**Comment by congheng** [comment]
remove check_hash from load_state_dict_from url() wthich in torch\resnest.py can solve the problem.
