### ISSUE TITLE
Couldn't inference on Gluoncv

### ISSUE THREAD

**Issue by ataata107** [zhanghang1989/ResNeSt#97]
Some of your models like Resnest_200 and Resnest_269 are not available for inference through gluoncv as it shows the model files are unavailable. Any way I can check the above models on ADE20K.
I even tried through encoding but it was showing error of enclib_gpu/enclib_cpu whenever I tried to import it.

**Comment by zhanghang1989** [comment]
For issues with GluonCV, please report it on their github repo. 

You can also download gluon model from this repo. Please update to the newest version.
